name: Lint
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - uses: c-hive/gha-yarn-cache@v1
        
        - name: Install dependencies
          run: yarn
          
        - name: Lint
          run: yarn lint
