name: Typescript
on: [push]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - uses: c-hive/gha-yarn-cache@v1
        
        - name: Install dependencies
          run: yarn
  
        - name: Check Typescript
          run: yarn tsc
