name: Typescript
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
    typescript:
        name: Typescript
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        
        - uses: c-hive/gha-yarn-cache@v1
        
        - name: Install dependencies
          run: yarn
  
        - name: Check Typescript
          run: yarn tsc
